#!/usr/bin/python

import socket
import threading
import argparse
import os
import json
import glob
import time
import re

def run_server(host, opt):
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        listener.bind((host, opt.port))
        listener.listen(5)
        if args.debugging:
            print('Echo server is listening at', opt.port)
        while True:
            conn, addr = listener.accept()
            threading.Thread(target=handle_client, args=(conn, addr, opt)).start()
    finally:
        listener.close()


def handle_client(conn, addr, opt):
    if opt.debugging:
        print '\n\nNew client from', addr
    try:
        while True:
            data = conn.recv(1024)
            if not data:
                break
            request_split = split_request(data)
            method_tuple = get_method(request_split[0])
            args.is_directory = method_tuple[1].endswith("/")

            if opt.debugging:
                print "Is directory? ", opt.is_directory

            path = re.search(r"\.{0,1}\w+\/*(\.{0,1}\w+\/*)*", method_tuple[1])
            if path is None:
                path = ""
            else:
                path = path.group(0)

            # print method_tuple
            if method_tuple[0] == "GET":
                if opt.debugging:
                    print "Data ", data
                send_get_data(request_split[0], conn, path, opt)
                break
            elif method_tuple[0] == "POST":
                if opt.debugging:
                    print "Data ", data
                send_post_data(request_split, conn, path, opt)
                break
            else:
                body = make_return_header(None, 0, "")
                conn.sendall(body)
                break

    finally:
        conn.close()

def split_request(data):
    return data.split("\r\n\r\n")

def get_method(headers):
    return headers.split()[:2]

def send_post_data(request, conn, path, opt):

    if opt.debugging:
        print "Debug Path ", path

    if not opt.is_directory and len(request) == 2:
        try:
            filename = glob.glob(os.path.join(opt.directory, path + '.*'))[0]
            if opt.debugging:
                print "Filename ", filename
            with open(filename, 'w') as myfile:
                myfile.write(request[1])
                data = make_return_header(True, 0, "")
        except IndexError, e:
            if opt.debugging:
                print "Error, ", str(e)
            data = make_return_header(False, 0, "")
    else:
        data = make_return_header(False, 0, "")
    conn.sendall(data)

def send_get_data(headers, conn, path, opt):
    if opt.debugging:
        print "Debug Path ", path

    if not opt.is_directory:
        try:
            filename = glob.glob(os.path.join(opt.directory, path + '.*'))[0]
            if opt.debugging:
                print "Filename ", filename
            with open(filename, 'r') as myfile:
                file_data = myfile.read()
                file_length = len(file_data)
                data = make_return_header(True, file_length, "text/plain")
                data += file_data + "\r\n"
        except (IndexError, OSError), e:
            if opt.debugging:
                print "Error ",str(e)
            data = make_return_header(False, 0, "")
    else:
        folder_path = os.path.join(opt.directory, path)
        file_data = "Folder path: " + folder_path + "\n"
        file_data += json.dumps(os.listdir(folder_path))
        file_length = len(file_data)
        data = make_return_header(True, file_length, "text/plain")
        data += file_data + "\r\n"
    conn.sendall(data)

def make_return_header(ok, length, content_type):
    header_string = ""
    if ok is True:
        header_string += "HTTP/1.0 200 OK\r\n"
    elif ok is False:
        header_string += "HTTP/1.0 404 Not Found\r\n"
    else:
        header_string += "HTTP/1.0 400 Bad Request\r\n"

    current_date = time.strftime("%a, %d %b %Y %H:%M:%S", time.localtime())
    header_string += "Date: " + current_date + "\r\n"
    header_string += "Server: Simple Python Server\r\n"

    if length > 0:
        header_string += "Content-Type: " + content_type + "\r\n"
        header_string += "Content-Length: " + str(length) + "\r\n"
    header_string += "\r\n"
    return header_string

# Usage python echoserver.py [--port port-number]
parser = argparse.ArgumentParser()
parser.add_argument("-p", action="store", dest="port", help="Set server port", type=int, default=8080)
parser.add_argument("-v", action="store_true", dest="debugging", help="Echo debugging mesages", default=False)
parser.add_argument("-d", action="store", dest="directory", help="Set directory path", default='/')
args = parser.parse_args()

args.is_directory = False

run_server('', args)
